[package]
name = "imm-wasm"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
imm-core = { path = "../imm-core", default-features = false }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Headers", "RequestInit", "Response"] }
